name: AppTest

on:
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t flask-app .

    - name: Run container in background
      run: docker run -d -p 8080:8080 --name flask-app-container flask-app

    - name: Test application
      run: |
        sleep 10 # Czekamy, aż aplikacja się uruchomi
        curl -f http://localhost:8080 || exit 1

    - name: Stop and remove container
      run: |
        docker stop flask-app-container
        docker rm flask-app-container
